#!/bin/zsh

# Get current directory and desired directory
current_dir=`pwd`
desired_dir=$HOME/Desktop/

# Check my current working directory and switch to in $HOME/Desktop/
if [ current_dir != desired_dir ]; then
    cd ~/Desktop/
fi

# Create new directory using webpack-template.
rsync -av --progress ~/webpack-template ~/Desktop --exclude node_modules --exclude .git --exclude coverage --exclude yarn.lock --exclude package.json --exclude tsconfig.json

# Add default package.json
cp ~/package.json ~/Desktop/webpack-template

# Change the name of webpack-template to something the user provides
if [ -n "$1" ]; then
    project_name=$1
    mv ~/Desktop/webpack-template $project_name
    cd $project_name
    echo
else
    echo
    echo -n "Please enter a project name: "
    read project_name
    mv ~/Desktop/webpack-template $project_name
    cd $project_name
    echo
fi

# Add default typescript configuration file
echo
echo "Creating tsconfig.json file."
echo
tsc --init
echo

# Install webpack dependencies
yarn init

# Instal webpack packages via yarn
install-webpack-config

# Friendly output
echo

if [ -n "$1" ]; then
    echo "Your new project $1 was successfuly created."
else
    echo "Your new project $default_name was successfuly created."
fi

echo
